// @no-log
GET http://api_cebv.test/api/personas?filter[nombre]=&filter[apellido_paterno]=&filter[apellido_materno]=
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "reporte_id": 7
}
