# This is a basic workflow to help us to deploy the Sicebv project
# This workflow will build a .NET project targeting Windows x64
# and create a release in the repository with the generated executable
# For more information see: https://docs.github.com/es/actions/writing-workflows/quickstart
name: "Deploy Sicebv"

on:
  push:
    tags:
      - "sicebv/v*"

permissions: write-all

env:
  PROJECT_PATH: Cebv/Cebv.csproj
  PUBLISH_PATH: Cebv/bin/Release/net8.0-windows/win-x64/publish/*.exe

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.404

      - run: dotnet clean ${{ env.PROJECT_PATH }}

      - run: dotnet restore ${{ env.PROJECT_PATH }} -r win-x64

      - run: dotnet build ${{ env.PROJECT_PATH }} -c Release

      - run: dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true

      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - uses: csexton/release-asset-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: ${{ env.PUBLISH_PATH }}
          release-url: ${{ steps.create_release.outputs.upload_url }}