# This is a basic workflow to help us to deploy the Sicebv project
# This workflow will build a .NET project targeting Windows x64
# and create a release in the repository with the generated executable
# For more information see: https://docs.github.com/es/actions/writing-workflows/quickstart
name: "Deploy Sicebv"

on:
  push:
    tags:
      - "sicebv/v*"

permissions:
  contents: write

env:
  PROJECT_PATH: Cebv/Cebv.csproj
  PUBLISH_PATH: publish_output/*.exe

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Publish Application
        run: |
          dotnet publish ${{ env.PROJECT_PATH }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=true -o publish_output

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          generate_release_notes: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.PUBLISH_PATH }}
          asset_name: Sicebv.exe
          asset_content_type: application/octet-stream
